# Generated by Django 3.2 on 2023-01-25 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Nickname')),
                ('age', models.PositiveSmallIntegerField(blank=True, verbose_name='Age')),
                ('city', models.CharField(blank=True, max_length=124, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=124, verbose_name='Country')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('genre', models.ManyToManyField(to='musicians.Genre', verbose_name='Genres of music')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of post')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.song', verbose_name='Songs')),
            ],
        ),
    ]
