# Generated by Django 3.2 on 2023-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_musician_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='songs',
        ),
        migrations.AddField(
            model_name='musician',
            name='songs',
            field=models.ManyToManyField(blank=True, to='musicians.Song', verbose_name='Songs'),
        ),
    ]
