# Generated by Django 3.2 on 2023-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_alter_musician_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genre',
            field=models.ManyToManyField(blank=True, to='musicians.Genre', verbose_name='Genres of music'),
        ),
    ]
