# Generated by Django 3.2 on 2023-01-30 13:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicians', '0006_userfavoritemusicians'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavoritemusicians',
            options={'verbose_name_plural': 'User favorite musicians'},
        ),
        migrations.AddField(
            model_name='musician',
            name='listeners',
            field=models.ManyToManyField(related_name='musicians', through='musicians.UserFavoriteMusicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musician',
            name='post_author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author of post'),
        ),
    ]
