# Generated by Django 3.2 on 2023-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0007_auto_20230130_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritemusicians',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Awesome'), (4, 'Good'), (3, 'Ok'), (2, 'Meh'), (1, 'Bad')], null=True),
        ),
    ]
