# Generated by Django 3.2 on 2023-01-31 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicians', '0008_alter_userfavoritemusicians_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSongRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('in_favorite', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(5, 'Awesome'), (4, 'Good'), (3, 'Ok'), (2, 'Meh'), (1, 'Bad')], null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
