# Generated by Django 3.2.16 on 2023-01-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0009_usersongrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavoritemusicians',
            options={'verbose_name_plural': 'User musicians rating'},
        ),
        migrations.AlterModelOptions(
            name='usersongrelation',
            options={'verbose_name_plural': 'User songs rating'},
        ),
        migrations.AddField(
            model_name='musician',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
